

c:dir
	gcc -o build/selection.c selection.c

cpp:dir
	g++ -o build/selection.cpp selection.cpp

go:dir
	gccgo -g -o build/selection.go selection.go

java:dir
	javac -d build/ selection.java

dir:
	mkdir -p build

clean:
	rm -rf build/

