

c:dir
	gcc -o build/gnome.c gnome.c

cpp:dir
	g++ -o build/gnome.cpp gnome.cpp

go:dir
	gccgo -g -o build/gnome.go gnome.go

java:dir
	javac -d build/ gnome.java

dir:
	mkdir -p build

clean:
	rm -rf build/
