

c:dir
	gcc -o build/bubble.c bubble.c

cpp:dir
	g++ -o build/bubble.cpp bubble.cpp

go:dir
	gccgo -g -o build/bubble.go bubble.go

java:dir
	javac -d build/ bubble.java

dir:
	mkdir -p build

clean:
	rm -rf build/
